language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-26.0.2
    - android-26
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
after_success:
  - bash <(curl -s https://codecov.io/bash)
